# Generated by Django 5.1.3 on 2024-11-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='complete_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='target',
            name='complete_state',
            field=models.BooleanField(default=False),
        ),
    ]
